openapi: 3.0.0
info:
  title: OpenAPI load specification for PUBLIC.FUGERIT.ADDRESS'
  description: 'Comments : Contains addresses data'
  version: '1.0.0'
servers:
  - url: http://localhost:9080/fugerit-sample-web/jax-rs/address/load
    description: Local Development server
paths:
  /id/{id}:
    get:
      summary: Get PUBLIC.FUGERIT.ADDRESS by primary key
      parameters:
        - name: id
          in: path
          required: true
          description: Value of field ID
          schema:
            type: string
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
  /all:
    get:
      summary: Get all PUBLIC.FUGERIT.ADDRESS
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                  type: array
                  items: 
                    $ref: '#/components/schemas/Address'
components: 
  schemas: 
    Address: 
      properties:
        id:
          type: string
          example: ''
        id_user:
          type: string
          example: ''
        date_insert:
          type: string
          example: ''
        date_update:
          type: string
          example: ''
        info:
          type: string
          example: ''
