swagger: '2.0'
info:
  description: 'Comments : Contains addresses data'
  title: 'OpenAPI load specification for PUBLIC.FUGERIT.ADDRESS'
  version: '1.0.0'
host: localhost:9080
schemes:
  - http
basePath: /ansc-app/jaxrs/address/load
paths:
  /id/{id}:
    get:
      summary: Get PUBLIC.FUGERIT.ADDRESS by primary key
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Value of field ID
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              id:
                type: string
                example: ''
              id_user:
                type: string
                example: ''
              date_insert:
                type: string
                example: ''
              date_update:
                type: string
                example: ''
              info:
                type: string
                example: ''
  /all:
    get:
      summary: Get all PUBLIC.FUGERIT.ADDRESS
      responses:
        '200':
          description: Success response
          schema:
              type: array
              items: 
                type: object
                properties:
                  id:
                    type: string
                    example: ''
                  id_user:
                    type: string
                    example: ''
                  date_insert:
                    type: string
                    example: ''
                  date_update:
                    type: string
                    example: ''
                  info:
                    type: string
                    example: ''
