openapi: 3.0.0
info:
  title: OpenAPI load specification for PUBLIC.FUGERIT.LOG_DATA'
  description: 'Comments : '
  version: '1.0.0'
servers:
  - url: http://localhost:9080/fugerit-sample-web/jax-rs/logdata/load
    description: Local Development server
paths:
  /all:
    get:
      summary: Get all PUBLIC.FUGERIT.LOG_DATA
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                  type: array
                  items: 
                    $ref: '#/components/schemas/LogData'
components: 
  schemas: 
    LogData: 
      properties:
        id:
          type: string
          example: ''
        logTime:
          type: string
          example: ''
        info:
          type: string
          example: ''
