openapi: 3.0.0
info:
  title: OpenAPI load specification for PUBLIC.FUGERIT.UPLOAD'
  description: 'Comments : Contains upload blob'
  version: '1.0.0'
servers:
  - url: http://localhost:9080/fugerit-sample-web/jax-rs/upload/load
    description: Local Development server
paths:
  /id/{id}:
    get:
      summary: Get PUBLIC.FUGERIT.UPLOAD by primary key
      parameters:
        - name: id
          in: path
          required: true
          description: Value of field ID
          schema:
            type: string
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upload'
  /all:
    get:
      summary: Get all PUBLIC.FUGERIT.UPLOAD
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                  type: array
                  items: 
                    $ref: '#/components/schemas/Upload'
components: 
  schemas: 
    Upload: 
      properties:
        id:
          type: string
          example: ''
        dateInsert:
          type: string
          example: ''
        dateUpdate:
          type: string
          example: ''
        content:
          type: string
          example: ''
