openapi: 3.0.0
info:
  title: OpenAPI load specification for PUBLIC.FUGERIT.USER_DATA'
  description: 'Comments : Contains users data'
  version: '1.0.0'
servers:
  - url: http://localhost:9080/fugerit-sample-web/jax-rs/userdata/load
    description: Local Development server
paths:
  /id/{id}:
    get:
      summary: Get PUBLIC.FUGERIT.USER_DATA by primary key
      parameters:
        - name: id
          in: path
          required: true
          description: Value of field ID
          schema:
            type: string
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
  /all:
    get:
      summary: Get all PUBLIC.FUGERIT.USER_DATA
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                  type: array
                  items: 
                    $ref: '#/components/schemas/UserData'
components: 
  schemas: 
    UserData: 
      properties:
        id:
          type: string
          example: ''
        username:
          type: string
          example: ''
        password:
          type: string
          example: ''
        lastLogin:
          type: string
          example: ''
        dateInsert:
          type: string
          example: ''
        dateUpdate:
          type: string
          example: ''
        state:
          type: string
          example: ''
